### ISSUE TITLE
Most show 10 tabs?

### ISSUE THREAD

**Issue by Iy204** [s2marine/vimperator-buftabs#1]
firefox 48.02
windows 10 1607
vimperator 3.14.0

**Comment by s2marine** [comment]
It depends on your screen resolution and scrollable tabbar is not support yet.

**Comment by Iy204** [comment]
希望能够支持，pentadactyl上面的那个就不错。
另外能够支持下配色方案么。

**Comment by s2marine** [comment]
vimperator-buftabs supports scrollable bar now. c3a68aeae04da4dd9174a16b06b707529ca67f69
You can change style by direct edit CSS at the source code. Maybe I'll extract it out as CSS file in sometime.
Pull requests are always welcome.
